In [5]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

x=datasets.load_iris()
X=x.data
Y=x.target



In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25)

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
pipe=Pipeline([])

pipe.fit(X_train,Y_train)
print

[Pipeline] ............... (step 1 of 3) Processing pca, total=   0.0s
[Pipeline] ............... (step 2 of 3) Processing std, total=   0.0s
[Pipeline] ..... (step 3 of 3) Processing decision_tree, total=   0.0s
{'memory': None, 'steps': [('pca', PCA(n_components=2)), ('std', StandardScaler()), ('decision_tree', DecisionTreeClassifier())], 'verbose': True, 'pca': PCA(n_components=2), 'std': StandardScaler(), 'decision_tree': DecisionTreeClassifier(), 'pca__copy': True, 'pca__iterated_power': 'auto', 'pca__n_components': 2, 'pca__n_oversamples': 10, 'pca__power_iteration_normalizer': 'auto', 'pca__random_state': None, 'pca__svd_solver': 'auto', 'pca__tol': 0.0, 'pca__whiten': False, 'std__copy': True, 'std__with_mean': True, 'std__with_std': True, 'decision_tree__ccp_alpha': 0.0, 'decision_tree__class_weight': None, 'decision_tree__criterion': 'gini', 'decision_tree__max_depth': None, 'decision_tree__max_features': None, 'decision_tree__max_leaf_nodes': None, 'decision_tree__min_impuri

In [5]:
import pandas as pd
data = pd.read_csv("C:/Users/hussam/Desktop/Catogorical_Columns/melb_data.csv")
data.head()

Suburb           Address  Rooms Type      Price Method SellerG   
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin  \
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea   
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN  \
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname   
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan  \
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

numerical_transformer = SimpleImputer(strategy='constant')

# Preprocessing for categorical data
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])


Rooms      Price  Distance  Postcode  Bedroom2  Bathroom  Car   
0          2  1480000.0       2.5    3067.0       2.0       1.0  1.0  \
1          2  1035000.0       2.5    3067.0       2.0       1.0  0.0   
2          3  1465000.0       2.5    3067.0       3.0       2.0  0.0   
3          3   850000.0       2.5    3067.0       3.0       2.0  1.0   
4          4  1600000.0       2.5    3067.0       3.0       1.0  2.0   
...      ...        ...       ...       ...       ...       ...  ...   
13575      4  1245000.0      16.7    3150.0       4.0       2.0  2.0   
13576      3  1031000.0       6.8    3016.0       3.0       2.0  2.0   
13577      3  1170000.0       6.8    3016.0       3.0       2.0  4.0   
13578      4  2500000.0       6.8    3016.0       4.0       1.0  5.0   
13579      4  1285000.0       6.3    3013.0       4.0       1.0  1.0   

       Landsize  BuildingArea  YearBuilt  ...  CouncilArea_Yarra   
0         202.0           NaN        NaN  ...               True  \
1         156.0          79.0     1900.0  ...               True   
2         134.0         150.0     1900.0  ...               True   
3          94.0           NaN        NaN  ...               True   
4         120.0         142.0     2014.0  ...               True   
...         ...           ...        ...  ...                ...   
13575     652.0           NaN     1981.0  ...              False   
13576     333.0         133.0     1995.0  ...              False   
13577     436.0           NaN     1997.0  ...              False   
13578     866.0         157.0     1920.0  ...              False   
13579     362.0         112.0     1920.0  ...              False   

       CouncilArea_Yarra Ranges  Regionname_Eastern Metropolitan   
0                         False                            False  \
1                         False                            False   
2                         False                            False   
3                         False                            False   
4                         False                            False   
...                         ...                              ...   
13575                     False                            False   
13576                     False                            False   
13577                     False                            False   
13578                     False                            False   
13579                     False                            False   

       Regionname_Eastern Victoria  Regionname_Northern Metropolitan   
0                            False                              True  \
1                            False                              True   
2                            False                              True   
3                            False                              True   
4                            False                              True   
...                            ...                               ...   
13575                        False                             False   
13576                        False                             False   
13577                        False                             False   
13578                        False                             False   
13579                        False                             False   

       Regionname_Northern Victoria  Regionname_South-Eastern Metropolitan   
0                             False                                  False  \
1                             False                                  False   
2                             False                                  False   
3                             False                                  False   
4                             False                                  False   
...                             ...                                    ...   
13575                         False                                   True   
13576              

In [1]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=1480000, strategy="most_frequent")
imputer.fit(pd.array(data['Price']).reshape(-1,1))

d = imputer.transform(pd.array(data['Price']).reshape(-1, 1))
print(d)

NameError: name 'pd' is not defined

In [11]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Normalizer

ct=ColumnTransformer(
    [('norm1',Normalizer(norm="l1"),[0,1,2,3]),
     ('norm2', Normalizer(norm="max"), [0, 1, 2, 3])]
)
X=np.array([[0,1,2,2],[1,1,0,1]])
print(X)
ct.fit_transform(X)

[[0 1 2 2]
 [1 1 0 1]]


array([[0.        , 0.2       , 0.4       , 0.4       , 0.        ,
        0.5       , 1.        , 1.        ],
       [0.33333333, 0.33333333, 0.        , 0.33333333, 1.        ,
        1.        , 0.        , 1.        ]])

In [28]:
ll='abdbababa'
ll=pd.get_dummies(pd.Series(list(ll)))
print(ll)

       a      b      d
0   True  False  False
1  False   True  False
2  False  False   True
3  False   True  False
4   True  False  False
5  False   True  False
6   True  False  False
7  False   True  False
8   True  False  False


### pipeline Scratch

In [ ]:
from xgboost import 